/*=============================================== Utils ===============================================*/

import * as utils from "ts-utils-julseb"

export const {
    calculateAverage,
    calculateTotalSum,
    capitalize,
    convertDate,
    convertDateShort,
    convertPrice,
    convertToEmail,
    convertToPascal,
    convertYoutube,
    detectLanguage,
    formatHour,
    generateNumbers,
    getFirstName,
    getLastName,
    getPercentage,
    getRandom,
    getRandomAvatar,
    getRandomDate,
    getRandomNumber,
    getRandomString,
    getRandomTime,
    getTimeNow,
    getToday,
    emailRegex,
    passwordRegex,
    scrollToTop,
    slugify,
    stringifyPx,
    unslugify,
    uuid,
} = utils
