/*=============================================== Utils ===============================================*/

export {
    calculateAverage,
    calculateTotalSum,
    camelToCapitalize,
    capitalize,
    convertDate,
    convertDateShort,
    convertPrice,
    convertToEmail,
    convertToPascal,
    convertYoutube,
    deleteDuplicates,
    detectLanguage,
    formatHour,
    generateNumbers,
    getFirstName,
    getLastName,
    getPercentage,
    getRandom,
    getRandomAvatar,
    getRandomDate,
    getRandomNumber,
    getRandomString,
    getRandomTime,
    getTimeNow,
    getToday,
    getTomorrow,
    emailRegex,
    passwordRegex,
    scrollToTop,
    slugify,
    stringifyPx,
    unslugify,
    uuid,
} from "ts-utils-julseb"
