/*=============================================== Utils ===============================================*/

import { v4 as uuid } from "uuid"
import {
    calculateTotalSum,
    capitalize,
    convertDate,
    convertDateShort,
    convertPrice,
    convertToEmail,
    convertToPascal,
    convertYoutube,
    detectLanguage,
    generateNumbers,
    getFirstName,
    getLastName,
    getPercentage,
    getRandom,
    getRandomAvatar,
    getRandomDate,
    getRandomNumber,
    getRandomString,
    getRandomTime,
    getTimeNow,
    getToday,
    emailRegex,
    passwordRegex,
    scrollToTop,
    slugify,
    stringifyPx,
    unslugify,
} from "ts-utils-julseb"

export {
    calculateTotalSum,
    capitalize,
    convertDate,
    convertDateShort,
    convertPrice,
    convertToEmail,
    convertToPascal,
    convertYoutube,
    detectLanguage,
    generateNumbers,
    getFirstName,
    getLastName,
    getPercentage,
    getRandom,
    getRandomAvatar,
    getRandomDate,
    getRandomNumber,
    getRandomString,
    getRandomTime,
    getTimeNow,
    getToday,
    emailRegex,
    passwordRegex,
    scrollToTop,
    slugify,
    stringifyPx,
    unslugify,
    uuid,
}
